My solution for CodeForces problem #548
idlv75/dragons-and-princesses pull request #14
Opened 2021-06-03 23:53 UTC by YifatYank

2021-06-14 06:24 UTC, idlv75 requested changes
Please see comments inline

2021-06-14 06:24 UTC, idlv75 commented on main.py
> +        file = open(file_name)
The Input should be in yaml format.
You are handling it as text file.
Can you implement the same with the standard Python yaml library?

2021-06-14 16:28 UTC, YifatYank commented on main.py
> +        file = open(file_name)
yes, I will

2021-06-21 15:50 UTC, idlv75 commented
Invited for interview

2021-06-21 15:50 UTC, closed without merging